spring:
  application:
    name: pawmart-ecommerce-backend

  datasource:
    url: jdbc:postgresql://localhost:5434/PawMart_db?options=-c%20TimeZone=UTC
    username: NCiDy
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.flywaydb: DEBUG
    org.postgresql: DEBUG

cloudinary:
  cloud-name: tlbzxewq
  api-key: 832884887827513
  api-secret: RsaOx0742CZWqlT6pVqhgiS8YOE

server:
  port: 8080

